default namespace = "http://www.w3.org/2007/01/ss-example#"

class Book
   property title : xs:string
   property author : Person+
   property firstPublished: xs:datetime?

class Person
   property name: xs:string
   property born: xs:datetime?
   property died: xs:datetime?
